[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "kuplift"
version = "0.0.5"
description = "A User Parameter-free Bayesian Framework for Uplift Modeling"
readme = "README.md"
requires-python = ">=3.10"
license-files = ["LICENSE"]
maintainers = [{name="The Khiops Team", email="khiops.team@orange.com"}]
dependencies = [
    "numpy",
    "pandas",
    "sortedcontainers",
    "scikit-learn",
    "khiops>=10.3.2.1",
    "umodl-wrapper>=0.0.11"
]

[project.optional-dependencies]
docs = [
    "sphinx>=5.3.0",
    "furo>=0.22.2",
    "numpydoc>=1.5.0",
    "sphinx-copybutton>=0.5.0"
]
test = [
    "pytest"
]

[tool.setuptools]
packages = ["kuplift"]
